//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCTBank.MobilApp.HGSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HGSService.HGSServiceSoap")]
    public interface HGSServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki customerTCKN öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaleHGS", ReplyAction="*")]
        JCTBank.MobilApp.HGSService.SaleHGSResponse SaleHGS(JCTBank.MobilApp.HGSService.SaleHGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaleHGS", ReplyAction="*")]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.SaleHGSResponse> SaleHGSAsync(JCTBank.MobilApp.HGSService.SaleHGSRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki PlateNumber öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadBalance", ReplyAction="*")]
        JCTBank.MobilApp.HGSService.LoadBalanceResponse LoadBalance(JCTBank.MobilApp.HGSService.LoadBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.LoadBalanceResponse> LoadBalanceAsync(JCTBank.MobilApp.HGSService.LoadBalanceRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki PlateNumber öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBalance", ReplyAction="*")]
        JCTBank.MobilApp.HGSService.UpdateBalanceResponse UpdateBalance(JCTBank.MobilApp.HGSService.UpdateBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.UpdateBalanceResponse> UpdateBalanceAsync(JCTBank.MobilApp.HGSService.UpdateBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleHGSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleHGS", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.SaleHGSRequestBody Body;
        
        public SaleHGSRequest() {
        }
        
        public SaleHGSRequest(JCTBank.MobilApp.HGSService.SaleHGSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleHGSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal balance;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int customerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customerTCKN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string plateNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime saleDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string webOrMobil;
        
        public SaleHGSRequestBody() {
        }
        
        public SaleHGSRequestBody(decimal balance, int customerId, string customerTCKN, string plateNumber, System.DateTime saleDate, string webOrMobil) {
            this.balance = balance;
            this.customerId = customerId;
            this.customerTCKN = customerTCKN;
            this.plateNumber = plateNumber;
            this.saleDate = saleDate;
            this.webOrMobil = webOrMobil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleHGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleHGSResponse", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.SaleHGSResponseBody Body;
        
        public SaleHGSResponse() {
        }
        
        public SaleHGSResponse(JCTBank.MobilApp.HGSService.SaleHGSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleHGSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaleHGSResult;
        
        public SaleHGSResponseBody() {
        }
        
        public SaleHGSResponseBody(bool SaleHGSResult) {
            this.SaleHGSResult = SaleHGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadBalance", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.LoadBalanceRequestBody Body;
        
        public LoadBalanceRequest() {
        }
        
        public LoadBalanceRequest(JCTBank.MobilApp.HGSService.LoadBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlateNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal balance;
        
        public LoadBalanceRequestBody() {
        }
        
        public LoadBalanceRequestBody(string PlateNumber, decimal balance) {
            this.PlateNumber = PlateNumber;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.LoadBalanceResponseBody Body;
        
        public LoadBalanceResponse() {
        }
        
        public LoadBalanceResponse(JCTBank.MobilApp.HGSService.LoadBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoadBalanceResult;
        
        public LoadBalanceResponseBody() {
        }
        
        public LoadBalanceResponseBody(bool LoadBalanceResult) {
            this.LoadBalanceResult = LoadBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBalance", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.UpdateBalanceRequestBody Body;
        
        public UpdateBalanceRequest() {
        }
        
        public UpdateBalanceRequest(JCTBank.MobilApp.HGSService.UpdateBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlateNumber;
        
        public UpdateBalanceRequestBody() {
        }
        
        public UpdateBalanceRequestBody(string PlateNumber) {
            this.PlateNumber = PlateNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public JCTBank.MobilApp.HGSService.UpdateBalanceResponseBody Body;
        
        public UpdateBalanceResponse() {
        }
        
        public UpdateBalanceResponse(JCTBank.MobilApp.HGSService.UpdateBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBalanceResult;
        
        public UpdateBalanceResponseBody() {
        }
        
        public UpdateBalanceResponseBody(bool UpdateBalanceResult) {
            this.UpdateBalanceResult = UpdateBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HGSServiceSoapChannel : JCTBank.MobilApp.HGSService.HGSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HGSServiceSoapClient : System.ServiceModel.ClientBase<JCTBank.MobilApp.HGSService.HGSServiceSoap>, JCTBank.MobilApp.HGSService.HGSServiceSoap {
        
        public HGSServiceSoapClient() {
        }
        
        public HGSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HGSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HGSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HGSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCTBank.MobilApp.HGSService.SaleHGSResponse JCTBank.MobilApp.HGSService.HGSServiceSoap.SaleHGS(JCTBank.MobilApp.HGSService.SaleHGSRequest request) {
            return base.Channel.SaleHGS(request);
        }
        
        public bool SaleHGS(decimal balance, int customerId, string customerTCKN, string plateNumber, System.DateTime saleDate, string webOrMobil) {
            JCTBank.MobilApp.HGSService.SaleHGSRequest inValue = new JCTBank.MobilApp.HGSService.SaleHGSRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.SaleHGSRequestBody();
            inValue.Body.balance = balance;
            inValue.Body.customerId = customerId;
            inValue.Body.customerTCKN = customerTCKN;
            inValue.Body.plateNumber = plateNumber;
            inValue.Body.saleDate = saleDate;
            inValue.Body.webOrMobil = webOrMobil;
            JCTBank.MobilApp.HGSService.SaleHGSResponse retVal = ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).SaleHGS(inValue);
            return retVal.Body.SaleHGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.SaleHGSResponse> JCTBank.MobilApp.HGSService.HGSServiceSoap.SaleHGSAsync(JCTBank.MobilApp.HGSService.SaleHGSRequest request) {
            return base.Channel.SaleHGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.SaleHGSResponse> SaleHGSAsync(decimal balance, int customerId, string customerTCKN, string plateNumber, System.DateTime saleDate, string webOrMobil) {
            JCTBank.MobilApp.HGSService.SaleHGSRequest inValue = new JCTBank.MobilApp.HGSService.SaleHGSRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.SaleHGSRequestBody();
            inValue.Body.balance = balance;
            inValue.Body.customerId = customerId;
            inValue.Body.customerTCKN = customerTCKN;
            inValue.Body.plateNumber = plateNumber;
            inValue.Body.saleDate = saleDate;
            inValue.Body.webOrMobil = webOrMobil;
            return ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).SaleHGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCTBank.MobilApp.HGSService.LoadBalanceResponse JCTBank.MobilApp.HGSService.HGSServiceSoap.LoadBalance(JCTBank.MobilApp.HGSService.LoadBalanceRequest request) {
            return base.Channel.LoadBalance(request);
        }
        
        public bool LoadBalance(string PlateNumber, decimal balance) {
            JCTBank.MobilApp.HGSService.LoadBalanceRequest inValue = new JCTBank.MobilApp.HGSService.LoadBalanceRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.LoadBalanceRequestBody();
            inValue.Body.PlateNumber = PlateNumber;
            inValue.Body.balance = balance;
            JCTBank.MobilApp.HGSService.LoadBalanceResponse retVal = ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).LoadBalance(inValue);
            return retVal.Body.LoadBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.LoadBalanceResponse> JCTBank.MobilApp.HGSService.HGSServiceSoap.LoadBalanceAsync(JCTBank.MobilApp.HGSService.LoadBalanceRequest request) {
            return base.Channel.LoadBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.LoadBalanceResponse> LoadBalanceAsync(string PlateNumber, decimal balance) {
            JCTBank.MobilApp.HGSService.LoadBalanceRequest inValue = new JCTBank.MobilApp.HGSService.LoadBalanceRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.LoadBalanceRequestBody();
            inValue.Body.PlateNumber = PlateNumber;
            inValue.Body.balance = balance;
            return ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).LoadBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCTBank.MobilApp.HGSService.UpdateBalanceResponse JCTBank.MobilApp.HGSService.HGSServiceSoap.UpdateBalance(JCTBank.MobilApp.HGSService.UpdateBalanceRequest request) {
            return base.Channel.UpdateBalance(request);
        }
        
        public bool UpdateBalance(string PlateNumber) {
            JCTBank.MobilApp.HGSService.UpdateBalanceRequest inValue = new JCTBank.MobilApp.HGSService.UpdateBalanceRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.UpdateBalanceRequestBody();
            inValue.Body.PlateNumber = PlateNumber;
            JCTBank.MobilApp.HGSService.UpdateBalanceResponse retVal = ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).UpdateBalance(inValue);
            return retVal.Body.UpdateBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.UpdateBalanceResponse> JCTBank.MobilApp.HGSService.HGSServiceSoap.UpdateBalanceAsync(JCTBank.MobilApp.HGSService.UpdateBalanceRequest request) {
            return base.Channel.UpdateBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<JCTBank.MobilApp.HGSService.UpdateBalanceResponse> UpdateBalanceAsync(string PlateNumber) {
            JCTBank.MobilApp.HGSService.UpdateBalanceRequest inValue = new JCTBank.MobilApp.HGSService.UpdateBalanceRequest();
            inValue.Body = new JCTBank.MobilApp.HGSService.UpdateBalanceRequestBody();
            inValue.Body.PlateNumber = PlateNumber;
            return ((JCTBank.MobilApp.HGSService.HGSServiceSoap)(this)).UpdateBalanceAsync(inValue);
        }
    }
}
